export class States {
  public stateList: any = [
    { id: 1, value: 'Jammu & Kashmir' },
    { id: 2, value: 'Himachal Pradesh' },
    { id: 3, value: 'Punjab' },
    { id: 4, value: 'Chandigarh' },
    { id: 5, value: 'Uttarakhand' },
    { id: 6, value: 'Haryana' },
    { id: 7, value: 'Delhi' },
    { id: 8, value: 'Rajasthan' },
    { id: 9, value: 'Uttar Pradesh' },
    { id: 10, value: 'Bihar' },
    { id: 11, value: 'Sikkim' },
    { id: 12, value: 'Arunachal Pradesh' },
    { id: 13, value: 'Nagaland' },
    { id: 14, value: 'Manipur' },
    { id: 15, value: 'Mizoram' },
    { id: 16, value: 'Tripura' },
    { id: 17, value: 'Meghalaya' },
    { id: 18, value: 'Assam' },
    { id: 19, value: 'West Bengal' },
    { id: 20, value: 'Jharkhand' },
    { id: 21, value: 'Odisha' },
    { id: 22, value: 'Chhattisgarh' },
    { id: 23, value: 'Madhya Pradesh' },
    { id: 24, value: 'Gujarat' },
    { id: 25, value: 'Daman & Diu' },
    { id: 26, value: 'Dadra & Nagar Haveli' },
    { id: 27, value: 'Maharashtra' },
    { id: 28, value: 'Karnataka' },
    { id: 29, value: 'Goa' },
    { id: 30, value: 'Lakshdweep' },
    { id: 31, value: 'Kerala' },
    { id: 32, value: 'Tamil Nadu' },
    { id: 32, value: 'Tamil Nadu' },
    { id: 33, value: 'Pondicherry' },
    { id: 34, value: 'Andaman & Nicobar Islands' },
    { id: 35, value: 'Telengana' },
    { id: 36, value: 'Andhra Pradesh' },
    { id: 97, value: 'Other Territory' },
  ];

  constructor(public id: number, public name: string) {}
}
